### PR TITLE
Profile (the name of the branch is a lie)

### PR DESCRIPTION
**Pull request by gvalkov**
Hello and kudos for the nice project.

I have a few modifications - mostly refactoring, profiling and small features - to vcprompt that I though you might find worthwhile. I ended up hacking all this in one branch so it's a bit messy. All tests pass, but I haven't gotten around to writing tests for the new placeholders.

Cheers,
Georgi

### CODE REVIEW

**Comment by djl** [comment]
Thanks for this :)

I'm not going merge these changes in. There's individual parts I'd like from a number of commits, but they're all tied together so I can't just merge them :(

The main issue is that a decent chunk of your changes will be lost in an upcoming refactor (each system is now a class with each "feature" being a method).

I'll comment on each commit in a little more detail.

**Comment by djl** [comment]
Also, there's a ton of PEP8 issues with your changes - 33 to be exact:

```
$ pep8 --count bin/vcprompt                                                                                                                                                                    [git:(unknown)]
bin/vcprompt:75:9: E203 whitespace before ':'
bin/vcprompt:75:31: E241 multiple spaces after ','
bin/vcprompt:91:1: E302 expected 2 blank lines, found 1
bin/vcprompt:228:80: E501 line too long (86 characters)
bin/vcprompt:267:14: E702 multiple statements on one line (semicolon)
bin/vcprompt:269:19: E701 multiple statements on one line (colon)
bin/vcprompt:496:23: E225 missing whitespace around operator
bin/vcprompt:530:41: E221 multiple spaces before operator
33
```

**Comment by gvalkov** [comment]
Oh, ok ... everything sounds reasonable :) I'll split things up into topic branches and let you know.

Refactoring things into classes sounds fine (for readability and overall niceness I suppose), but I must admit I really liked how functional-ish everything was so far :) - it gets things done (quickly) and that is usually the most important part.

**Comment by gvalkov** [comment]
Actually, maybe it would be better if you finished your refactoring first and then I redo my changes. Maybe even have a 'next' or 'wip' branch so that this effort could be parallelized between people?

**Comment by gvalkov** [comment]
pep8 is nice and all, but the paragraph about hobgoblins is perhaps the most worthwhile read of the whole pep :)

**Comment by gvalkov** [comment]
Hate to resurrect a closed pull request but ...

There were some pretty reasonable changes here, that I think improved readability and performance to some degree. If you won't be going ahead with your  `class-per-vcs`, would you mind if I resubmitted the pull request?

My two cents on factoring out the vcs functionality into classes is that there's just not that much to gain from it, except for a bit of readability.

**Comment by djl** [comment]
> Hate to resurrect a closed pull request but ...

Woah, I don't remember closing this at all!

> There were some pretty reasonable changes here, that I think improved readability and performance to some degree.

Which commit includes the readability improvements? [fdcc771](https://github.com/gvalkov/vcprompt/commit/fdcc7711e7fac2e4d856b1b6dae998402a23aa86)? IMO, neither [this](https://github.com/gvalkov/vcprompt/blob/fdcc7711e7fac2e4d856b1b6dae998402a23aa86/bin/vcprompt#L74-88) nor [this](https://github.com/gvalkov/vcprompt/blob/fdcc7711e7fac2e4d856b1b6dae998402a23aa86/bin/vcprompt#L266-270) is readable _at all_.

Ninja edit: This sounded _way_ more sarcastic than I intended :(

What I meant was that a large dictionary with vague tuple values is harder for my brain to parse than what is currently there.

> My two cents on factoring out the vcs functionality into classes is that there's just not that much to gain from it, except for a bit of readability.

Agreed completely here. A few weeks ago to abandon that in favor of a 'lite' branch which I've been using locally (and I intend to make public at some point).

**Comment by gvalkov** [comment]
Sure, thanks for the reply - I had pretty much forgotten about this as well and decided to ask just by the way if there was a chance to resurrect this.

Well, the biggest improvement was supposed to be in the fact that dict lookup ( `O(1)` ) would be used instead of string lookup, eg:

``` python
# the current branch is required to get the sha
if 'b' in ph or 'r' in ph or 'h' in ph:
```

instead of

``` python
# the current branch is required to get the sha
if re.search('%(b|r|h)', options.format):
```

The placeholder dict is a bit unparsable because it tries to store all the info for the available placeholders as well as the info needed to generate the output of '--help-format'. With slight changes to `helperFormat()`, the placeholders dict can be rewritten as the slightly more readable:

``` python
# Dictionary of:
#   placeholder : placeholder,
#                 description as seen in --help-format,
#                 group to which the placeholder belongs,
placeholders = {
's'  : ('repository type',            'Common Placeholders'),
'b'  : ('branch',                     'Common Placeholders'),
'r'  : ('revision',                   'Common Placeholders'),
'h'  : ('revision',                   'Common Placeholders'),
'm'  : ('modified flag',              'Common Placeholders'),
'mc' : ('modified file count',        'Common Placeholders'),
'u'  : ('untracked flag',             'Common Placeholders'),
'uc' : ('untracked file count',       'Common Placeholders'),
'a'  : ('staged flag',                'Git'      ),
'ac' : ('staged file count',          'Git'      ),
'sc' : ('stash count',                'Git'      ),
'tb' : ('tracked branch',             'Git', 'Hg'),
'tr' : ('revision of tracked branch', 'Git', 'Hg'),
}
```

As for the second snippet of code, it can be just rewritten as 

``` python
for k in placeholders.iterkeys():
    if k in options.format:
        options.format_placeholders[k] = None
```

at the expense of having instance instead of local variable lookups. I admit that I tend to prefer terseness to pep8 compliance in certain cases.

It would also be nice if an `entry_point` was used instead of a `script` in setup.py, so that python can actually reuse the byte-compilation (free speedup).

Anyway, best of luck with the 'lite' branch :)

**Pull request closed without merging**
