### PR TITLE
set utf-8

### PR DESCRIPTION
**Pull request by insanehong**
Add utf-9 encoding code for using custom status symbol
## Example

```
# status indicators
STAGED = os.environ.get('VCPROMPT_STAGED', '⚙')
MODIFIED = os.environ.get('VCPROMPT_MODIFIED', '±')
UNTRACKED = os.environ.get('VCPROMPT_UNTRACKED', '✘')
```

### CODE REVIEW

**Comment by djl** [comment]
UTF-8 already works? Am I overlooking something?

```
$ touch foo
$ VCPROMPT_UNTRACKED="✘" vcprompt -f "%u"
✘
```

**Comment by insanehong** [comment]
When I executed vcprompt, I get the next Syntax Error:

1 bash 2013-09-09 20-17-36

```
  File "/Users/insanehong/.vcprompt/vcprompt", line 74
SyntaxError: Non-ASCII character '\xe2' in file /Users/insanehong/.vcprompt/vcprompt on line 74, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

**Comment by djl** [comment]
Don't edit the file to add your new symbols, instead set the environment variables:

```
export VCPROMPT_STAGED="⚙"
export VCPROMPT_MODIFIED="±"
export VCPROMPT_UNTRACKED="✘"
```

**Comment by insanehong** [comment]
I got it. Thanks!

**Comment by insanehong** [comment]
clean problens

1 sh 2013-09-09 21-08-12

Thanks ^^

**Pull request closed without merging**
